// <auto-generated />
using System;
using Conbot.ModerationPlugin;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Conbot.ModerationPlugin.Migrations
{
    [DbContext(typeof(ModerationContext))]
    partial class ModerationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Conbot.ModerationPlugin.ModerationGuildConfiguration", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigurations");
                });

            modelBuilder.Entity("Conbot.ModerationPlugin.PreconfiguredMutedRole", b =>
                {
                    b.Property<ulong>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId");

                    b.ToTable("PreconfiguredMutedRoles");
                });

            modelBuilder.Entity("Conbot.ModerationPlugin.TemporaryMutedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("GuildId", "UserId");

                    b.ToTable("TemporaryMutedUsers");
                });

            modelBuilder.Entity("Conbot.ModerationPlugin.TemporaryMutedUser", b =>
                {
                    b.HasOne("Conbot.ModerationPlugin.ModerationGuildConfiguration", "GuildConfiguration")
                        .WithMany("TemporaryMutedUsers")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfiguration");
                });

            modelBuilder.Entity("Conbot.ModerationPlugin.ModerationGuildConfiguration", b =>
                {
                    b.Navigation("TemporaryMutedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
