// <auto-generated />
using Conbot.PrefixPlugin;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Conbot.PrefixPlugin.Migrations
{
    [DbContext(typeof(PrefixContext))]
    partial class PrefixContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Conbot.PrefixPlugin.Prefix", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "Text");

                    b.ToTable("Prefixes");
                });
#pragma warning restore 612, 618
        }
    }
}
